name = "MWE"
uuid = "3792e1f2-778c-4a37-80b2-082962570cee"
authors = ["Knut Andreas Meyer and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
